### ISSUE TITLE
Support for Broadcasting Streams

### ISSUE THREAD

**Issue by beberlei** [wildbit/swiftmailer-postmark#28]
The Swiftmailer transport for Postmark does not support broadcasting streams yet. 

The method `getMessagePayload` needs to check for the `X-PM-Message-Stream` header defined in the docs to set the `"streams"` json key:

https://github.com/wildbit/swiftmailer-postmark/blob/master/src/Postmark/Transport.php#L167

https://postmarkapp.com/support/article/1207-how-to-create-and-send-through-message-streams

**Comment by vladsandu** [comment]
@beberlei Thank you for submitting this PR and sorry for the delayed reply here.

As discussed in #20 , we want to defer most of this work to the API so that customers don't need to update their clients as frequently/when we add new functionality.

The Postmark API already supports setting the `MessageStream` via either the `MessageStream` field or the `X-PM-Message-Stream` header, like it's done for SMTP. 

I have just tested this and can confirm that `swiftmailer-postmark` supports setting the `MessageStream` per message via:
```php
$message->getHeaders()->addTextHeader('X-PM-Message-Stream', 'your-custom-stream');
```

The ability to set the `MessageStream` at transport-level might be useful for customers and we'll look over the PR and consider that as well, but you should already be able to set this at message-level.
